services:
  postgres:
    image: postgres:latest
    container_name: florence_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: florence_redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "${SEARXNG_HOST_PORT}:8080"
    volumes:
      - searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    restart: unless-stopped

  api:
    build: .
    container_name: florence_api
    ports:
      - "${API_HOST_PORT}:7055"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  admin:
    build: .
    container_name: florence_admin
    command: uvicorn src.admin:admin_app --uds /tmp/admin.sock --chmod-socket 666
    volumes:
      - /tmp:/tmp
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  searxng: