services:
  postgres:
    image: postgres:latest
    container_name: florence_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: florence_redis
    ports:
      - "5434:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
